"use client";

import { FileText } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Submission {
  studentName?: string;
  studentId?: string;
  studentBranch?: string;
  studentYear?: string;
  score?: number;
  totalQuestions?: number;
  percentage?: number;
  totalTimeUsed?: number;
}

interface ExamSessionPDFButtonProps {
  sessionName: string;
  submissions: Submission[];
  collegeName: string;
}

export default function ExamSessionPDFButton({
  sessionName,
  submissions,
  collegeName,
}: ExamSessionPDFButtonProps) {
  const fmt = (s: number) =>
    `${Math.floor(s / 60).toString().padStart(2, "0")}:${(s % 60).toString().padStart(2, "0")}`;

  const avg = submissions.length > 0
    ? Math.round(submissions.reduce((acc, s) => acc + (s.percentage ?? 0), 0) / submissions.length)
    : 0;
  const highest = submissions[0]?.percentage ?? 0;
  const lowest = submissions[submissions.length - 1]?.percentage ?? 0;
  const passRate = submissions.length > 0
    ? Math.round((submissions.filter((s) => (s.percentage ?? 0) >= 40).length / submissions.length) * 100)
    : 0;

  const handleDownload = () => {
    const rows = submissions
      .map(
        (s, i) => `
      <tr class="${i % 2 === 0 ? "" : "alt"} ${(s.percentage ?? 0) >= 40 ? "pass" : "fail"}">
        <td class="rank">${i === 0 ? "🥇" : i === 1 ? "🥈" : i === 2 ? "🥉" : i + 1}</td>
        <td>
          <strong>${s.studentName ?? "—"}</strong><br/>
          <span class="mono">${s.studentId ?? ""}</span>
        </td>
        <td>${s.studentBranch ?? "—"}</td>
        <td>Year ${s.studentYear ?? "—"}</td>
        <td><strong>${s.score ?? 0}/${s.totalQuestions ?? "?"}</strong></td>
        <td class="${(s.percentage ?? 0) >= 40 ? "text-green" : "text-red"}">${s.percentage ?? 0}%</td>
        <td>${fmt(s.totalTimeUsed ?? 0)}</td>
      </tr>`
      )
      .join("");

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>${sessionName} Results — ${collegeName}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Inter',Arial,sans-serif; background:#fff; color:#1a1a2e; padding:40px; font-size:13px; line-height:1.6; }
  .header { background:linear-gradient(135deg,#7c3aed,#4f46e5); color:white; padding:28px 32px; border-radius:16px; margin-bottom:24px; }
  .header h1 { font-size:22px; font-weight:800; margin-bottom:4px; }
  .header p { opacity:0.8; font-size:13px; }
  .stats { display:flex; gap:14px; margin-bottom:24px; }
  .stat { flex:1; border:2px solid #e5e7eb; border-radius:12px; padding:14px; text-align:center; }
  .stat .val { font-size:26px; font-weight:800; }
  .stat .lbl { font-size:11px; color:#6b7280; margin-top:4px; font-weight:500; }
  .stat.g { border-color:#10b981; color:#10b981; }
  .stat.b { border-color:#3b82f6; color:#3b82f6; }
  .stat.p { border-color:#7c3aed; color:#7c3aed; }
  .stat.o { border-color:#f59e0b; color:#f59e0b; }
  table { width:100%; border-collapse:collapse; }
  th { background:#f3f4f6; text-align:left; padding:10px 14px; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:0.05em; color:#6b7280; }
  td { padding:11px 14px; border-bottom:1px solid #f3f4f6; font-size:12px; }
  tr.alt td { background:#fafafa; }
  td.rank { font-weight:700; font-size:15px; text-align:center; }
  .mono { font-family:monospace; color:#9ca3af; font-size:11px; }
  .text-green { color:#10b981; font-weight:700; }
  .text-red { color:#ef4444; font-weight:700; }
  .footer { margin-top:32px; text-align:center; color:#9ca3af; font-size:11px; border-top:1px solid #e5e7eb; padding-top:16px; }
</style>
</head>
<body>
<div class="header">
  <h1>📊 ${sessionName} — Exam Results</h1>
  <p>${collegeName} &nbsp;|&nbsp; ${submissions.length} Students &nbsp;|&nbsp; Generated on ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</p>
</div>
<div class="stats">
  <div class="stat g"><div class="val">${avg}%</div><div class="lbl">Avg Score</div></div>
  <div class="stat g"><div class="val">${highest}%</div><div class="lbl">Highest</div></div>
  <div class="stat b"><div class="val">${lowest}%</div><div class="lbl">Lowest</div></div>
  <div class="stat p"><div class="val">${passRate}%</div><div class="lbl">Pass Rate (≥40%)</div></div>
  <div class="stat o"><div class="val">${submissions.length}</div><div class="lbl">Total Students</div></div>
</div>
<table>
  <thead><tr><th>#</th><th>Student</th><th>Branch</th><th>Year</th><th>Score</th><th>Percentage</th><th>Time Used</th></tr></thead>
  <tbody>${rows}</tbody>
</table>
<div class="footer">Generated by VoxIntel &nbsp;|&nbsp; ${sessionName} · ${collegeName}</div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      win.onload = () => { win.print(); URL.revokeObjectURL(url); };
    }
  };

  return (
    <Button
      onClick={handleDownload}
      variant="outline"
      size="sm"
      className="border-primary-200/30 text-primary-200 hover:bg-primary-200/10 gap-2 font-semibold rounded-xl"
    >
      <FileText size={14} />
      Download PDF
    </Button>
  );
}
